name: Deep Forest Sync

on:
  push:
    branches:
      - master
      # for testing
      - jayden/deep-forest-multi-folder

jobs:
  deploy:
    name: Deploy pickles JSONs to GCP Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.STATIC_SITE_ACTIONS_GCP_SERVICE_ACCOUNT }}"

      - id: setup_gcp
        name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0

      - name: Node Setup 16.x
        id: setup_node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install picklesdoc
        id: picklesdoc
        run: npm install -g picklesdoc@latest

      - name: Generate pickles JSON
        id: picklesdoc_generate
        run: picklesdoc json ./packages saasquatch__program-tools__at__master.json

      - name: Deploy to bucket
        id: gcp_rsync
        run: gsutil cp saasquatch__program-tools__at__master.json gs://deep-forest-pickles.ssqt.io/
