name: Visual Dev Storyshot Tests

on:
  push:
    branches: [main, master]
    paths:
      - packages/visual-dev/**
  pull_request:
    paths:
      - packages/visual-dev/**

env:
  # opt out of storybook data harvesting
  STORYBOOK_DISABLE_TELEMETRY: "1"
  STORYBOOK_ENABLE_CRASH_REPORTS: "0"
  # make sure Puppeteer isn't using an ancient Chromium
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  # https://github.com/actions/runner-images/blob/releases/ubuntu22/20230109/images/linux/scripts/installers/google-chrome.sh#L96
  PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"

jobs:
  run-storyshot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: NPM install
        working-directory: packages/visual-dev
        run: npm install

      - name: Run snapshot tests
        working-directory: packages/visual-dev
        continue-on-error: true
        run: |
          npm run storybook &
          # 20 attempts, 6 seconds each = 2 minute wait for Storybook to start
          for _attempt in {1..20}; do
            sleep 6
            if curl http://localhost:9001/ --silent >/dev/null; then
              echo "Connected to storybook!"
              break
            fi
            echo "Waiting for storybook..."; done
          npm test

      - name: Upload diffs
        uses: actions/upload-artifact@v3
        with:
          name: diff-output
          path: packages/visual-dev/src/__tests__/__image_snapshots__/__diff_output__/
